"""Initial

Revision ID: cde6f97f64b4
Revises: 
Create Date: 2023-08-01 08:54:51.143798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde6f97f64b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('payment_guarantees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.String(length=124), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=124), nullable=True),
    sa.Column('last_name', sa.String(length=124), nullable=True),
    sa.Column('cell_phone_number', sa.String(length=124), nullable=True),
    sa.Column('email', sa.String(length=124), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_guarantees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_guarantees_ref_id'), ['ref_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_guarantees_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_guarantees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_guarantees_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_guarantees_ref_id'))

    op.drop_table('payment_guarantees')
    op.drop_table('users')
    # ### end Alembic commands ###
